# Conditionallt install a package based on OS
---
- name: Conditionallt install a package based on OS
  hosts: all
  become: true
  tasks:
    - name: Install nginx on Ubuntu/Debian server
      apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian"
      
    - name: Install APache httpd on RedHat/Centos server  
      yum:
        name: httpd
        state: present
      notify: Start and Enable Service  #Because apache needs to start and enabled after installation otherwise webpage will not be reached.
      when: ansible_facts['os_family'] == "RedHat"

  handlers:
    - name: Start and Enable Service
      service:
        name: httpd
        state: started
        enabled: yes



# Note:
# If using different OS from the ansible controller one then state that in your inventory file as:
# For example if your ansible controller is on ubuntu then
# private_ip ansible_user=ec2-user
