# Create multiple users and set password using vault
---
- name: Create multiple users and set password using vault
  hosts: all
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: Create user
      user:
        name: "{{item.name}}"
        password: "{{item.password | password_hash('sha512')}}"
        shell: /bin/bash
        state: present
      loop: "{{users}}"


# Sample secrets.yml
# ---
# users:
#    - name: user1
#      password: "user1"
#    - name: user2
#      password: "user2"
#    - name: user3
#      password: "user3"
