#Gather and display system facts of all servers using setup module to collect information like OS, IP,hostname.
---
- name: Gather and Display system facts via setup module
  hosts: all
  become: yes
  tasks:
    - name: Setup module
      setup:
    - name: Display system facts
      debug:
        msg: 
         - "IP: {{ansible_default_ipv4.address}}"
         - "OS: {{ansible_distribution}}"
         - "Hostname: {{ansible_hostname}}"
