# Reboot servers and wait until they are up

---
- name: Reboot servers and wait until they are back
  hosts: test
  become: yes
  tasks:
    - name: Reboot servers
      reboot:
        reboot_timeout: 600
        test_command: whoami
