# Fetch a file from remote to Ansible Controller

---
- name: Fetch a file from remote hosts to controller
  hosts: all
  become: yes
  tasks:
    - name: Fetch file
      fetch:
        src: /home/ubuntu/temp.txt
        dest: /home/ubuntu/Temp/temp.txt
        flat: yes  # prevents Ansible from creating nested host directory(like ip/home/ubuntu/Temp/temp/txt for all nodes), it directly saves files to dest.
